# AI Explorer - Dependabot 依赖更新配置
version: 2
updates:
  # NPM 包依赖更新
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    reviewers:
      - "@me"
    assignees:
      - "@me"
    labels:
      - "dependencies"
      - "area/build"
      - "automated"
    versioning-strategy: increase
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # GitHub Actions 更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    reviewers:
      - "@me"
    assignees:
      - "@me"
    labels:
      - "dependencies"
      - "area/ci"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker 相关 (如果将来添加)
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"